#name: flow_flutter
#description: Projeto Maxtrack Flow agora na plataforma Flutter.
#publish_to: none
#
## The following defines the version and build number for your application.
## A version number is three numbers separated by dots, like 1.2.43
## followed by an optional build number separated by a +.
## Both the version and the builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
## Read more about versioning at semver.org.
#
#version: 2.0.85+132
#
#environment:
#  sdk: ">=2.6.0 <3.0.0"
#
#dependencies:
#  connectivity_plus: ^2.3.0
#
#  flutter:
#    sdk: flutter
#
#  flutter_localizations:
#    sdk: flutter
#
#  quiver: '>=2.0.0 <3.1.0'
#  file: ^6.1.4
#  collection: any
#  sentry_flutter: ^6.20.1
#  cupertino_icons: ^1.0.5
#  http: ^0.13.3
#  async_loader: ^0.1.2
#  shared_preferences: ^2.0.6
#  cached_network_image: ^3.2.3
#  rxdart: ^0.26.0
#  dartx: ^1.1.0
#  google_fonts: 2.2.0
#  auto_size_text: ^2.1.0
#  provider: ^6.0.0
#  bubble_tab_indicator: "^0.1.5"
#  #package_info: ^2.0.2
#  flutter_spinkit: ^5.0.0
#  image_picker: ^1.0.3
#  flutter_image_compress: ^1.0.0
#  hive: ^2.0.4
#  hive_flutter: ^1.1.0
#  geolocator: ^7.3.1
#  shifting_tabbar: ^1.0.2
#  transparent_image: ^2.0.0
#  hand_signature: ^2.1.0+2
#  path_provider: ^2.0.2
#  groovin_widgets: ^3.0.2
#  circular_menu: ^2.0.1
#  flutter_barcode_scanner: ^2.0.0
#  animated_stream_list: ^1.1.0
#  flutter_typeahead: ^3.2.0
#  email_validator: ^2.0.1
#  flutter_keyboard_visibility: ^5.0.3
#  toggle_switch: ^0.1.4
#  flutter_svg: ^0.22.0
#  list_treeview: ^0.2.5+1
#  ansicolor: ^2.0.1
#  flutter_exif_rotation: ^0.5.1
#  permission_handler: ^8.1.4+1
#  image_cropper: ^1.4.1
#  dropdown_search: ^5.0.6
#  flutter_vlc_player: ^6.0.5
#  image_size_getter: ^2.1.2
#  package_info_plus: ^3.0.0
#  version: ^3.0.0
#  pub_semver: ^2.0.0
#  device_info_plus: ^9.0.2
#  url_launcher: ^6.1.11
#  mailer: 4.0.0
#
#
#dev_dependencies:
#  hive_generator: ^1.1.0
#  build_runner: ^2.3.2
#  mockito: ^5.0.12
#  flutter_test:
#    sdk: flutter
#
#
#
#
##dependency_overrides:
##  analyzer: ^0.40.0
#
## For information on the generic Dart part of this file, see the
## following page: https://www.dartlang.org/tools/pub/pubspec
#
## The following section is specific to Flutter.
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#
#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/font/montserrat/Montserrat-Regular.ttf
#    - assets/font/montserrat/Montserrat-Italic.ttf
#    - assets/font/montserrat/Montserrat-Bold.ttf
#    - assets/font/FlowIcons.ttf
#    - assets/image/
#    - assets/json/
#  #  - images/a_dot_burr.jpeg
#  #  - images/a_dot_ham.jpeg
#
#  # An image asset can refer to one or more resolution-specific "variants", see
#  # https://flutter.io/assets-and-images/#resolution-aware.
#
#  # For details regarding adding assets from package dependencies, see
#  # https://flutter.io/assets-and-images/#from-packages
#
#  # To add custom fonts to your application, add a fonts section here,
#  # in this "flutter" section. Each entry in this list should have a
#  # "family" key with the font family name, and a "fonts" key with a
#  # list giving the asset and other descriptors for the font. For
#  # example:
#  fonts:
#    - family:  GoInstallationIcons
#      fonts:
#        - asset: assets/font/GoInstallationIcons.ttf
#
#    - family: Montserrat
#      fonts:
#        - asset: assets/font/montserrat/Montserrat-Regular.ttf
#        #           weight: 900
#        - asset: assets/font/montserrat/Montserrat-Italic.ttf
#        - asset: assets/font/montserrat/Montserrat-Bold.ttf
#    #           weight: 900
#
#    - family: FlowIcons
#      fonts:
#        - asset: assets/font/FlowIcons.ttf
#
#
#  # For details regarding fonts from package dependencies,
#  # see https://flutter.io/custom-fonts/#from-packages


name: flow_flutter
description: Projeto Maxtrack Flow agora na plataforma Flutter.
publish_to: none

version: 2.0.86+133

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  quiver: '>=2.0.0 <3.1.0'
  file: ^6.1.4
  collection: any
  sentry_flutter: ^6.20.1
  cupertino_icons: ^1.0.5
  http: ^0.13.3
  async_loader: ^0.1.2
  shared_preferences: ^2.0.6
  cached_network_image: ^3.2.3
  rxdart: ^0.26.0
  dartx: ^1.1.0
  google_fonts: 2.2.0
  auto_size_text: ^2.1.0
  provider: ^6.0.0
  bubble_tab_indicator: "^0.1.5"
  flutter_spinkit: ^5.0.0
  image_picker: ^1.0.3
  flutter_image_compress: ^1.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  geolocator: ^7.3.1
  shifting_tabbar: ^1.0.2
  transparent_image: ^2.0.0
  hand_signature: ^2.1.0+2
  path_provider: ^2.0.2
  groovin_widgets: ^3.0.2
  circular_menu: ^2.0.1
  flutter_barcode_scanner: ^2.0.0
  animated_stream_list: ^1.1.0
  flutter_typeahead: ^3.2.0
  email_validator: ^2.0.1
  flutter_keyboard_visibility: ^5.0.3
  toggle_switch: ^0.1.4
  flutter_svg: ^0.22.0
  list_treeview: ^0.2.5+1
  ansicolor: ^2.0.1
  flutter_exif_rotation: ^0.5.1
  permission_handler: ^8.1.4+1
  image_cropper: ^1.4.1
  dropdown_search: ^5.0.6
  flutter_vlc_player: ^6.0.5
  image_size_getter: ^2.1.2
  package_info_plus: ^3.0.0
  version: ^3.0.0
  pub_semver: ^2.0.0
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.11
  mailer: 4.0.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.3.2
  mockito: ^5.0.12
  flutter_test:
    sdk: flutter

dependency_overrides:
  xml: ^6.1.0
  ffi: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/font/montserrat/Montserrat-Regular.ttf
    - assets/font/montserrat/Montserrat-Italic.ttf
    - assets/font/montserrat/Montserrat-Bold.ttf
    - assets/font/FlowIcons.ttf
    - assets/image/
    - assets/json/

  fonts:
    - family: GoInstallationIcons
      fonts:
        - asset: assets/font/GoInstallationIcons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat/Montserrat-Regular.ttf
        - asset: assets/font/montserrat/Montserrat-Italic.ttf
        - asset: assets/font/montserrat/Montserrat-Bold.ttf

    - family: FlowIcons
      fonts:
        - asset: assets/font/FlowIcons.ttf