/// Flutter icons GoInstallationIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoInstallationIcons
///      fonts:
///       - asset: fonts/GoInstallationIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GoInstallationIcons {
  GoInstallationIcons._();

  static const _kFontFam = 'GoInstallationIcons';
  static const String _kFontPkg = null;

  static const IconData door_key =
      IconData(0xf101, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_key_filled =
      IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_charge =
      IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_level4 =
      IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_level3 =
      IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_level2 =
      IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_level1 =
      IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_empty =
      IconData(0xf108, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_fault =
      IconData(0xf109, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sos =
      IconData(0xf10a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone_filled =
      IconData(0xf10b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone =
      IconData(0xf10c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite_filled =
      IconData(0xf10d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favourite =
      IconData(0xf10e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xf10f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_filled =
      IconData(0xf110, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network =
      IconData(0xf111, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network_filled =
      IconData(0xf112, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route =
      IconData(0xf113, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geolocation =
      IconData(0xf114, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_open =
      IconData(0xf115, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xf116, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_error =
      IconData(0xf117, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_error_filled =
      IconData(0xf118, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_verify =
      IconData(0xf119, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_verify_filled =
      IconData(0xf11a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_star =
      IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_star_filled =
      IconData(0xf11c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData antenna =
      IconData(0xf11d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite_dish =
      IconData(0xf11e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite =
      IconData(0xf11f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wireless_charging =
      IconData(0xf120, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_parked =
      IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xf122, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning =
      IconData(0xf123, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen =
      IconData(0xf125, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen_exit =
      IconData(0xf126, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engine =
      IconData(0xf127, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xf128, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear =
      IconData(0xf129, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu =
      IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_filled =
      IconData(0xf12b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_warn =
      IconData(0xf12c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu_warn_filled =
      IconData(0xf12d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer =
      IconData(0xf12e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer_filled =
      IconData(0xf12f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list =
      IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office_building_filled =
      IconData(0xf131, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office_building =
      IconData(0xf132, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal =
      IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xf134, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_filled =
      IconData(0xf135, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xf136, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xf137, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xf138, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simcard =
      IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storage_warn =
      IconData(0xf13b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world_grid =
      IconData(0xf13c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xf13d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery =
      IconData(0xf13f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone =
      IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute =
      IconData(0xf141, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload =
      IconData(0xf142, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xf143, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer =
      IconData(0xf144, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xf145, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xf146, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xf147, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume1 =
      IconData(0xf148, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume2 =
      IconData(0xf149, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume3 =
      IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muted =
      IconData(0xf14b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password =
      IconData(0xf14c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information =
      IconData(0xf14d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode =
      IconData(0xf14e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coding =
      IconData(0xf14f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer =
      IconData(0xf150, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus =
      IconData(0xf151, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_filled =
      IconData(0xf152, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xf153, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_filled =
      IconData(0xf154, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike =
      IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike_filled =
      IconData(0xf156, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xf157, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled =
      IconData(0xf158, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man =
      IconData(0xf159, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify_circular =
      IconData(0xf15a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circular =
      IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circular =
      IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recycling_bin =
      IconData(0xf15d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      IconData(0xf15e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xf15f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages =
      IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_closed =
      IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_filled =
      IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_filled =
      IconData(0xf166, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network2_filled_1 =
      IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethernet =
      IconData(0xf168, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethernet_filled =
      IconData(0xf169, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint =
      IconData(0xf16a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop =
      IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_filled =
      IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_1 =
      IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driver_id =
      IconData(0xf16e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind_settings =
      IconData(0xf16f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind_settings_filled =
      IconData(0xf170, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_plug =
      IconData(0xf171, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_button =
      IconData(0xf172, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tap_button =
      IconData(0xf173, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal1 =
      IconData(0xf174, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal4 =
      IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal5 =
      IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal3 =
      IconData(0xf177, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal2 =
      IconData(0xf178, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bee =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_disconnected =
      IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow =
      IconData(0xf17b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi1 =
      IconData(0xf17c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi5 =
      IconData(0xf17d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi2 =
      IconData(0xf17e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi3 =
      IconData(0xf17f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi4 =
      IconData(0xf180, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bee_filled =
      IconData(0xf181, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment =
      IconData(0xf182, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xf183, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_arrow =
      IconData(0xf184, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graphic =
      IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart =
      IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart =
      IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      IconData(0xf188, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors =
      IconData(0xf189, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_box =
      IconData(0xf18a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xf18b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler =
      IconData(0xf18c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh2 =
      IconData(0xf18d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up2 =
      IconData(0xf18e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import =
      IconData(0xf18f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export =
      IconData(0xf190, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_wrench =
      IconData(0xf191, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_filled =
      IconData(0xf192, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xf193, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worker =
      IconData(0xf194, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setup =
      IconData(0xf195, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like =
      IconData(0xf196, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck =
      IconData(0xf197, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_filled =
      IconData(0xf198, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane =
      IconData(0xf199, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_filled =
      IconData(0xf19a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space_ship =
      IconData(0xf19b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleepy =
      IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase =
      IconData(0xf19d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi_board =
      IconData(0xf19e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ambulance =
      IconData(0xf19f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement =
      IconData(0xf1a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet =
      IconData(0xf1a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData race_flag =
      IconData(0xf1a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racing_game =
      IconData(0xf1a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tyre =
      IconData(0xf1a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter =
      IconData(0xf1a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helicopter_filled =
      IconData(0xf1a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain_bike =
      IconData(0xf1a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_up =
      IconData(0xf1a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor =
      IconData(0xf1aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paste =
      IconData(0xf1ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diskette =
      IconData(0xf1ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diskette_filled =
      IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_time =
      IconData(0xf1ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xf1af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_add =
      IconData(0xf1b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch =
      IconData(0xf1b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_star =
      IconData(0xf1b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock =
      IconData(0xf1b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_edit =
      IconData(0xf1b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_search =
      IconData(0xf1b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alarm =
      IconData(0xf1b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_check =
      IconData(0xf1b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_close =
      IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contract =
      IconData(0xf1ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package =
      IconData(0xf1bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trailer =
      IconData(0xf1bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static IconData getIcon(String key) {
    if (key == null) return car_filled;
    if (key.contains("flaticon-")) key = key.replaceFirst("flaticon-", "");
    key = key.replaceAll("-", "_");

    var returnValue = <String, dynamic>{
      'door_key': door_key,
      'door_key_filled': door_key_filled,
      'battery_charge': battery_charge,
      'battery_level4': battery_level4,
      'battery_level3': battery_level3,
      'battery_level2': battery_level2,
      'battery_level1': battery_level1,
      'battery_empty': battery_empty,
      'battery_fault': battery_fault,
      'sos': sos,
      'megaphone_filled': megaphone_filled,
      'megaphone': megaphone,
      'favourite_filled': favourite_filled,
      'favourite': favourite,
      'cloud': cloud,
      'cloud_filled': cloud_filled,
      'network': network,
      'network_filled': network_filled,
      'route': route,
      'geolocation': geolocation,
      'padlock_open': padlock_open,
      'unlock': unlock,
      'padlock_error': padlock_error,
      'padlock_error_filled': padlock_error_filled,
      'padlock_verify': padlock_verify,
      'padlock_verify_filled': padlock_verify_filled,
      'padlock_star': padlock_star,
      'padlock_star_filled': padlock_star_filled,
      'antenna': antenna,
      'satellite_dish': satellite_dish,
      'satellite': satellite,
      'wireless_charging': wireless_charging,
      'pin_parked': pin_parked,
      'pin': pin,
      'warning': warning,
      'arrow_up': arrow_up,
      'fullscreen': fullscreen,
      'fullscreen_exit': fullscreen_exit,
      'engine': engine,
      'settings': settings,
      'gear': gear,
      'cpu': cpu,
      'cpu_filled': cpu_filled,
      'cpu_warn': cpu_warn,
      'cpu_warn_filled': cpu_warn_filled,
      'printer': printer,
      'printer_filled': printer_filled,
      'list': list,
      'office_building_filled': office_building_filled,
      'office_building': office_building,
      'terminal': terminal,
      'send': send,
      'send_filled': send_filled,
      'history': history,
      'refresh': refresh,
      'clock': clock,
      'edit': edit,
      'simcard': simcard,
      'storage_warn': storage_warn,
      'world_grid': world_grid,
      'camera': camera,
      'image': image,
      'gallery': gallery,
      'microphone': microphone,
      'mute': mute,
      'cloud_upload': cloud_upload,
      'location': location,
      'transfer': transfer,
      'play': play,
      'pause': pause,
      'stop': stop,
      'volume1': volume1,
      'volume2': volume2,
      'volume3': volume3,
      'muted': muted,
      'password': password,
      'information': information,
      'qrcode': qrcode,
      'coding': coding,
      'thermometer': thermometer,
      'bus': bus,
      'bus_filled': bus_filled,
      'car': car,
      'car_filled': car_filled,
      'motorbike': motorbike,
      'motorbike_filled': motorbike_filled,
      'home': home,
      'home_filled': home_filled,
      'man': man,
      'verify_circular': verify_circular,
      'add_circular': add_circular,
      'close_circular': close_circular,
      'recycling_bin': recycling_bin,
      'bell': bell,
      'message': message,
      'messages': messages,
      'logout': logout,
      'email_closed': email_closed,
      'filter': filter,
      'filter_filled': filter_filled,
      'heart': heart,
      'heart_filled': heart_filled,
      'network2_filled_1': network2_filled_1,
      'ethernet': ethernet,
      'ethernet_filled': ethernet_filled,
      'fingerprint': fingerprint,
      'drop': drop,
      'drop_filled': drop_filled,
      'information_1': information_1,
      'driver_id': driver_id,
      'mind_settings': mind_settings,
      'mind_settings_filled': mind_settings_filled,
      'power_plug': power_plug,
      'power_button': power_button,
      'tap_button': tap_button,
      'signal1': signal1,
      'signal4': signal4,
      'signal5': signal5,
      'signal3': signal3,
      'signal2': signal2,
      'bee': bee,
      'cloud_disconnected': cloud_disconnected,
      'up_arrow': up_arrow,
      'wifi1': wifi1,
      'wifi5': wifi5,
      'wifi2': wifi2,
      'wifi3': wifi3,
      'wifi4': wifi4,
      'bee_filled': bee_filled,
      'attachment': attachment,
      'file': file,
      'double_arrow': double_arrow,
      'graphic': graphic,
      'bar_chart': bar_chart,
      'pie_chart': pie_chart,
      'clipboard': clipboard,
      'scissors': scissors,
      'open_box': open_box,
      'eye': eye,
      'ruler': ruler,
      'refresh2': refresh2,
      'arrow_up2': arrow_up2,
      'import': import,
      'export': export,
      'hand_wrench': hand_wrench,
      'user_filled': user_filled,
      'user': user,
      'worker': worker,
      'setup': setup,
      'like': like,
      'truck': truck,
      'truck_filled': truck_filled,
      'plane': plane,
      'plane_filled': plane_filled,
      'space_ship': space_ship,
      'sleepy': sleepy,
      'suitcase': suitcase,
      'wifi_board': wifi_board,
      'ambulance': ambulance,
      'tag': tag,
      'agreement': agreement,
      'helmet': helmet,
      'race_flag': race_flag,
      'racing_game': racing_game,
      'tyre': tyre,
      'helicopter': helicopter,
      'helicopter_filled': helicopter_filled,
      'mountain_bike': mountain_bike,
      'arrows_up': arrows_up,
      'monitor': monitor,
      'paste': paste,
      'diskette': diskette,
      'diskette_filled': diskette_filled,
      'calendar_time': calendar_time,
      'calendar': calendar,
      'calendar_add': calendar_add,
      'stopwatch': stopwatch,
      'calendar_star': calendar_star,
      'alarm_clock': alarm_clock,
      'calendar_edit': calendar_edit,
      'calendar_search': calendar_search,
      'calendar_alarm': calendar_alarm,
      'calendar_check': calendar_check,
      'calendar_close': calendar_close,
      'contract': contract,
      'package': package,
      'trailer': trailer
    }[key];
    if (returnValue == null)
      return home_filled;
    else
      return returnValue;
  }
}
