// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maxpb_adapter_control.proto

package maxpb;

public final class MaxpbAdapterControl {
  private MaxpbAdapterControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ControlConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.ControlConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> 
        getAdapterBaudrateList();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getAdapterBaudrate(int index);
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    int getAdapterBaudrateCount();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
        getAdapterBaudrateOrBuilderList();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getAdapterBaudrateOrBuilder(
        int index);

    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasFingerprint();
    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.lang.String getFingerprint();
    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    com.google.protobuf.ByteString
        getFingerprintBytes();

    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasVersionApp();
    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.lang.String getVersionApp();
    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionAppBytes();

    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasFileCommand();
    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbFiletransfer.FileCommand getFileCommand();
    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbFiletransfer.FileCommandOrBuilder getFileCommandOrBuilder();

    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> 
        getConnectedDevicesList();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getConnectedDevices(int index);
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    int getConnectedDevicesCount();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
        getConnectedDevicesOrBuilderList();
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getConnectedDevicesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code maxpb.ControlConfig}
   */
  public static final class ControlConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.ControlConfig)
      ControlConfigOrBuilder {
    // Use ControlConfig.newBuilder() to construct.
    private ControlConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ControlConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ControlConfig defaultInstance;
    public static ControlConfig getDefaultInstance() {
      return defaultInstance;
    }

    public ControlConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ControlConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                adapterBaudrate_ = new java.util.ArrayList<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice>();
                mutable_bitField0_ |= 0x00000001;
              }
              adapterBaudrate_.add(input.readMessage(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fingerprint_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              versionApp_ = bs;
              break;
            }
            case 34: {
              maxpb.MaxpbFiletransfer.FileCommand.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = fileCommand_.toBuilder();
              }
              fileCommand_ = input.readMessage(maxpb.MaxpbFiletransfer.FileCommand.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fileCommand_);
                fileCommand_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                connectedDevices_ = new java.util.ArrayList<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice>();
                mutable_bitField0_ |= 0x00000010;
              }
              connectedDevices_.add(input.readMessage(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          adapterBaudrate_ = java.util.Collections.unmodifiableList(adapterBaudrate_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          connectedDevices_ = java.util.Collections.unmodifiableList(connectedDevices_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbAdapterControl.internal_static_maxpb_ControlConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbAdapterControl.internal_static_maxpb_ControlConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbAdapterControl.ControlConfig.class, maxpb.MaxpbAdapterControl.ControlConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<ControlConfig> PARSER =
        new com.google.protobuf.AbstractParser<ControlConfig>() {
      public ControlConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ControlConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ADAPTERBAUDRATE_FIELD_NUMBER = 1;
    private java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> adapterBaudrate_;
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> getAdapterBaudrateList() {
      return adapterBaudrate_;
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
        getAdapterBaudrateOrBuilderList() {
      return adapterBaudrate_;
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public int getAdapterBaudrateCount() {
      return adapterBaudrate_.size();
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getAdapterBaudrate(int index) {
      return adapterBaudrate_.get(index);
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getAdapterBaudrateOrBuilder(
        int index) {
      return adapterBaudrate_.get(index);
    }

    public static final int FINGERPRINT_FIELD_NUMBER = 2;
    private java.lang.Object fingerprint_;
    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasFingerprint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.lang.String getFingerprint() {
      java.lang.Object ref = fingerprint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fingerprint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fingerprint = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFingerprintBytes() {
      java.lang.Object ref = fingerprint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSIONAPP_FIELD_NUMBER = 3;
    private java.lang.Object versionApp_;
    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasVersionApp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.lang.String getVersionApp() {
      java.lang.Object ref = versionApp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionApp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string versionApp = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionAppBytes() {
      java.lang.Object ref = versionApp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionApp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILECOMMAND_FIELD_NUMBER = 4;
    private maxpb.MaxpbFiletransfer.FileCommand fileCommand_;
    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasFileCommand() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbFiletransfer.FileCommand getFileCommand() {
      return fileCommand_;
    }
    /**
     * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbFiletransfer.FileCommandOrBuilder getFileCommandOrBuilder() {
      return fileCommand_;
    }

    public static final int CONNECTEDDEVICES_FIELD_NUMBER = 5;
    private java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> connectedDevices_;
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> getConnectedDevicesList() {
      return connectedDevices_;
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
        getConnectedDevicesOrBuilderList() {
      return connectedDevices_;
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public int getConnectedDevicesCount() {
      return connectedDevices_.size();
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getConnectedDevices(int index) {
      return connectedDevices_.get(index);
    }
    /**
     * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getConnectedDevicesOrBuilder(
        int index) {
      return connectedDevices_.get(index);
    }

    private void initFields() {
      adapterBaudrate_ = java.util.Collections.emptyList();
      fingerprint_ = "";
      versionApp_ = "";
      fileCommand_ = maxpb.MaxpbFiletransfer.FileCommand.getDefaultInstance();
      connectedDevices_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAdapterBaudrateCount(); i++) {
        if (!getAdapterBaudrate(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFileCommand()) {
        if (!getFileCommand().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getConnectedDevicesCount(); i++) {
        if (!getConnectedDevices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < adapterBaudrate_.size(); i++) {
        output.writeMessage(1, adapterBaudrate_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getFingerprintBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getVersionAppBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, fileCommand_);
      }
      for (int i = 0; i < connectedDevices_.size(); i++) {
        output.writeMessage(5, connectedDevices_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < adapterBaudrate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, adapterBaudrate_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFingerprintBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getVersionAppBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, fileCommand_);
      }
      for (int i = 0; i < connectedDevices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, connectedDevices_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.ControlConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbAdapterControl.ControlConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.ControlConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.ControlConfig)
        maxpb.MaxpbAdapterControl.ControlConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_ControlConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_ControlConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbAdapterControl.ControlConfig.class, maxpb.MaxpbAdapterControl.ControlConfig.Builder.class);
      }

      // Construct using maxpb.MaxpbAdapterControl.ControlConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAdapterBaudrateFieldBuilder();
          getFileCommandFieldBuilder();
          getConnectedDevicesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (adapterBaudrateBuilder_ == null) {
          adapterBaudrate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          adapterBaudrateBuilder_.clear();
        }
        fingerprint_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        versionApp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (fileCommandBuilder_ == null) {
          fileCommand_ = maxpb.MaxpbFiletransfer.FileCommand.getDefaultInstance();
        } else {
          fileCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (connectedDevicesBuilder_ == null) {
          connectedDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          connectedDevicesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_ControlConfig_descriptor;
      }

      public maxpb.MaxpbAdapterControl.ControlConfig getDefaultInstanceForType() {
        return maxpb.MaxpbAdapterControl.ControlConfig.getDefaultInstance();
      }

      public maxpb.MaxpbAdapterControl.ControlConfig build() {
        maxpb.MaxpbAdapterControl.ControlConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbAdapterControl.ControlConfig buildPartial() {
        maxpb.MaxpbAdapterControl.ControlConfig result = new maxpb.MaxpbAdapterControl.ControlConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (adapterBaudrateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            adapterBaudrate_ = java.util.Collections.unmodifiableList(adapterBaudrate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.adapterBaudrate_ = adapterBaudrate_;
        } else {
          result.adapterBaudrate_ = adapterBaudrateBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fingerprint_ = fingerprint_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.versionApp_ = versionApp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (fileCommandBuilder_ == null) {
          result.fileCommand_ = fileCommand_;
        } else {
          result.fileCommand_ = fileCommandBuilder_.build();
        }
        if (connectedDevicesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            connectedDevices_ = java.util.Collections.unmodifiableList(connectedDevices_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.connectedDevices_ = connectedDevices_;
        } else {
          result.connectedDevices_ = connectedDevicesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbAdapterControl.ControlConfig) {
          return mergeFrom((maxpb.MaxpbAdapterControl.ControlConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbAdapterControl.ControlConfig other) {
        if (other == maxpb.MaxpbAdapterControl.ControlConfig.getDefaultInstance()) return this;
        if (adapterBaudrateBuilder_ == null) {
          if (!other.adapterBaudrate_.isEmpty()) {
            if (adapterBaudrate_.isEmpty()) {
              adapterBaudrate_ = other.adapterBaudrate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAdapterBaudrateIsMutable();
              adapterBaudrate_.addAll(other.adapterBaudrate_);
            }
            onChanged();
          }
        } else {
          if (!other.adapterBaudrate_.isEmpty()) {
            if (adapterBaudrateBuilder_.isEmpty()) {
              adapterBaudrateBuilder_.dispose();
              adapterBaudrateBuilder_ = null;
              adapterBaudrate_ = other.adapterBaudrate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              adapterBaudrateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAdapterBaudrateFieldBuilder() : null;
            } else {
              adapterBaudrateBuilder_.addAllMessages(other.adapterBaudrate_);
            }
          }
        }
        if (other.hasFingerprint()) {
          bitField0_ |= 0x00000002;
          fingerprint_ = other.fingerprint_;
          onChanged();
        }
        if (other.hasVersionApp()) {
          bitField0_ |= 0x00000004;
          versionApp_ = other.versionApp_;
          onChanged();
        }
        if (other.hasFileCommand()) {
          mergeFileCommand(other.getFileCommand());
        }
        if (connectedDevicesBuilder_ == null) {
          if (!other.connectedDevices_.isEmpty()) {
            if (connectedDevices_.isEmpty()) {
              connectedDevices_ = other.connectedDevices_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureConnectedDevicesIsMutable();
              connectedDevices_.addAll(other.connectedDevices_);
            }
            onChanged();
          }
        } else {
          if (!other.connectedDevices_.isEmpty()) {
            if (connectedDevicesBuilder_.isEmpty()) {
              connectedDevicesBuilder_.dispose();
              connectedDevicesBuilder_ = null;
              connectedDevices_ = other.connectedDevices_;
              bitField0_ = (bitField0_ & ~0x00000010);
              connectedDevicesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConnectedDevicesFieldBuilder() : null;
            } else {
              connectedDevicesBuilder_.addAllMessages(other.connectedDevices_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAdapterBaudrateCount(); i++) {
          if (!getAdapterBaudrate(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasFileCommand()) {
          if (!getFileCommand().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getConnectedDevicesCount(); i++) {
          if (!getConnectedDevices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbAdapterControl.ControlConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbAdapterControl.ControlConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> adapterBaudrate_ =
        java.util.Collections.emptyList();
      private void ensureAdapterBaudrateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          adapterBaudrate_ = new java.util.ArrayList<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice>(adapterBaudrate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> adapterBaudrateBuilder_;

      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> getAdapterBaudrateList() {
        if (adapterBaudrateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(adapterBaudrate_);
        } else {
          return adapterBaudrateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public int getAdapterBaudrateCount() {
        if (adapterBaudrateBuilder_ == null) {
          return adapterBaudrate_.size();
        } else {
          return adapterBaudrateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getAdapterBaudrate(int index) {
        if (adapterBaudrateBuilder_ == null) {
          return adapterBaudrate_.get(index);
        } else {
          return adapterBaudrateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setAdapterBaudrate(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (adapterBaudrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.set(index, value);
          onChanged();
        } else {
          adapterBaudrateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setAdapterBaudrate(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (adapterBaudrateBuilder_ == null) {
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.set(index, builderForValue.build());
          onChanged();
        } else {
          adapterBaudrateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAdapterBaudrate(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (adapterBaudrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.add(value);
          onChanged();
        } else {
          adapterBaudrateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAdapterBaudrate(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (adapterBaudrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.add(index, value);
          onChanged();
        } else {
          adapterBaudrateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAdapterBaudrate(
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (adapterBaudrateBuilder_ == null) {
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.add(builderForValue.build());
          onChanged();
        } else {
          adapterBaudrateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAdapterBaudrate(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (adapterBaudrateBuilder_ == null) {
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.add(index, builderForValue.build());
          onChanged();
        } else {
          adapterBaudrateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAllAdapterBaudrate(
          java.lang.Iterable<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> values) {
        if (adapterBaudrateBuilder_ == null) {
          ensureAdapterBaudrateIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, adapterBaudrate_);
          onChanged();
        } else {
          adapterBaudrateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearAdapterBaudrate() {
        if (adapterBaudrateBuilder_ == null) {
          adapterBaudrate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          adapterBaudrateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder removeAdapterBaudrate(int index) {
        if (adapterBaudrateBuilder_ == null) {
          ensureAdapterBaudrateIsMutable();
          adapterBaudrate_.remove(index);
          onChanged();
        } else {
          adapterBaudrateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder getAdapterBaudrateBuilder(
          int index) {
        return getAdapterBaudrateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getAdapterBaudrateOrBuilder(
          int index) {
        if (adapterBaudrateBuilder_ == null) {
          return adapterBaudrate_.get(index);  } else {
          return adapterBaudrateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
           getAdapterBaudrateOrBuilderList() {
        if (adapterBaudrateBuilder_ != null) {
          return adapterBaudrateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(adapterBaudrate_);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder addAdapterBaudrateBuilder() {
        return getAdapterBaudrateFieldBuilder().addBuilder(
            maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance());
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder addAdapterBaudrateBuilder(
          int index) {
        return getAdapterBaudrateFieldBuilder().addBuilder(
            index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance());
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice adapterBaudrate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder> 
           getAdapterBaudrateBuilderList() {
        return getAdapterBaudrateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
          getAdapterBaudrateFieldBuilder() {
        if (adapterBaudrateBuilder_ == null) {
          adapterBaudrateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder>(
                  adapterBaudrate_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          adapterBaudrate_ = null;
        }
        return adapterBaudrateBuilder_;
      }

      private java.lang.Object fingerprint_ = "";
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasFingerprint() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.lang.String getFingerprint() {
        java.lang.Object ref = fingerprint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fingerprint_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFingerprintBytes() {
        java.lang.Object ref = fingerprint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fingerprint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setFingerprint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fingerprint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fingerprint_ = getDefaultInstance().getFingerprint();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fingerprint = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setFingerprintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fingerprint_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object versionApp_ = "";
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasVersionApp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.lang.String getVersionApp() {
        java.lang.Object ref = versionApp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            versionApp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionAppBytes() {
        java.lang.Object ref = versionApp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionApp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setVersionApp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        versionApp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearVersionApp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        versionApp_ = getDefaultInstance().getVersionApp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionApp = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setVersionAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        versionApp_ = value;
        onChanged();
        return this;
      }

      private maxpb.MaxpbFiletransfer.FileCommand fileCommand_ = maxpb.MaxpbFiletransfer.FileCommand.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          maxpb.MaxpbFiletransfer.FileCommand, maxpb.MaxpbFiletransfer.FileCommand.Builder, maxpb.MaxpbFiletransfer.FileCommandOrBuilder> fileCommandBuilder_;
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasFileCommand() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbFiletransfer.FileCommand getFileCommand() {
        if (fileCommandBuilder_ == null) {
          return fileCommand_;
        } else {
          return fileCommandBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setFileCommand(maxpb.MaxpbFiletransfer.FileCommand value) {
        if (fileCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileCommand_ = value;
          onChanged();
        } else {
          fileCommandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setFileCommand(
          maxpb.MaxpbFiletransfer.FileCommand.Builder builderForValue) {
        if (fileCommandBuilder_ == null) {
          fileCommand_ = builderForValue.build();
          onChanged();
        } else {
          fileCommandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder mergeFileCommand(maxpb.MaxpbFiletransfer.FileCommand value) {
        if (fileCommandBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              fileCommand_ != maxpb.MaxpbFiletransfer.FileCommand.getDefaultInstance()) {
            fileCommand_ =
              maxpb.MaxpbFiletransfer.FileCommand.newBuilder(fileCommand_).mergeFrom(value).buildPartial();
          } else {
            fileCommand_ = value;
          }
          onChanged();
        } else {
          fileCommandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearFileCommand() {
        if (fileCommandBuilder_ == null) {
          fileCommand_ = maxpb.MaxpbFiletransfer.FileCommand.getDefaultInstance();
          onChanged();
        } else {
          fileCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbFiletransfer.FileCommand.Builder getFileCommandBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getFileCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbFiletransfer.FileCommandOrBuilder getFileCommandOrBuilder() {
        if (fileCommandBuilder_ != null) {
          return fileCommandBuilder_.getMessageOrBuilder();
        } else {
          return fileCommand_;
        }
      }
      /**
       * <code>optional .maxpb.FileCommand fileCommand = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          maxpb.MaxpbFiletransfer.FileCommand, maxpb.MaxpbFiletransfer.FileCommand.Builder, maxpb.MaxpbFiletransfer.FileCommandOrBuilder> 
          getFileCommandFieldBuilder() {
        if (fileCommandBuilder_ == null) {
          fileCommandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              maxpb.MaxpbFiletransfer.FileCommand, maxpb.MaxpbFiletransfer.FileCommand.Builder, maxpb.MaxpbFiletransfer.FileCommandOrBuilder>(
                  getFileCommand(),
                  getParentForChildren(),
                  isClean());
          fileCommand_ = null;
        }
        return fileCommandBuilder_;
      }

      private java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> connectedDevices_ =
        java.util.Collections.emptyList();
      private void ensureConnectedDevicesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          connectedDevices_ = new java.util.ArrayList<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice>(connectedDevices_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> connectedDevicesBuilder_;

      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> getConnectedDevicesList() {
        if (connectedDevicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(connectedDevices_);
        } else {
          return connectedDevicesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public int getConnectedDevicesCount() {
        if (connectedDevicesBuilder_ == null) {
          return connectedDevices_.size();
        } else {
          return connectedDevicesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getConnectedDevices(int index) {
        if (connectedDevicesBuilder_ == null) {
          return connectedDevices_.get(index);
        } else {
          return connectedDevicesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setConnectedDevices(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (connectedDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectedDevicesIsMutable();
          connectedDevices_.set(index, value);
          onChanged();
        } else {
          connectedDevicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setConnectedDevices(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (connectedDevicesBuilder_ == null) {
          ensureConnectedDevicesIsMutable();
          connectedDevices_.set(index, builderForValue.build());
          onChanged();
        } else {
          connectedDevicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addConnectedDevices(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (connectedDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectedDevicesIsMutable();
          connectedDevices_.add(value);
          onChanged();
        } else {
          connectedDevicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addConnectedDevices(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice value) {
        if (connectedDevicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConnectedDevicesIsMutable();
          connectedDevices_.add(index, value);
          onChanged();
        } else {
          connectedDevicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addConnectedDevices(
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (connectedDevicesBuilder_ == null) {
          ensureConnectedDevicesIsMutable();
          connectedDevices_.add(builderForValue.build());
          onChanged();
        } else {
          connectedDevicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addConnectedDevices(
          int index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder builderForValue) {
        if (connectedDevicesBuilder_ == null) {
          ensureConnectedDevicesIsMutable();
          connectedDevices_.add(index, builderForValue.build());
          onChanged();
        } else {
          connectedDevicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder addAllConnectedDevices(
          java.lang.Iterable<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice> values) {
        if (connectedDevicesBuilder_ == null) {
          ensureConnectedDevicesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, connectedDevices_);
          onChanged();
        } else {
          connectedDevicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearConnectedDevices() {
        if (connectedDevicesBuilder_ == null) {
          connectedDevices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          connectedDevicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder removeConnectedDevices(int index) {
        if (connectedDevicesBuilder_ == null) {
          ensureConnectedDevicesIsMutable();
          connectedDevices_.remove(index);
          onChanged();
        } else {
          connectedDevicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder getConnectedDevicesBuilder(
          int index) {
        return getConnectedDevicesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder getConnectedDevicesOrBuilder(
          int index) {
        if (connectedDevicesBuilder_ == null) {
          return connectedDevices_.get(index);  } else {
          return connectedDevicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<? extends maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
           getConnectedDevicesOrBuilderList() {
        if (connectedDevicesBuilder_ != null) {
          return connectedDevicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(connectedDevices_);
        }
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder addConnectedDevicesBuilder() {
        return getConnectedDevicesFieldBuilder().addBuilder(
            maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance());
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder addConnectedDevicesBuilder(
          int index) {
        return getConnectedDevicesFieldBuilder().addBuilder(
            index, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance());
      }
      /**
       * <code>repeated .maxpb.MaxConfigAdapterDevice connectedDevices = 5;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public java.util.List<maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder> 
           getConnectedDevicesBuilderList() {
        return getConnectedDevicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder> 
          getConnectedDevicesFieldBuilder() {
        if (connectedDevicesBuilder_ == null) {
          connectedDevicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder, maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder>(
                  connectedDevices_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          connectedDevices_ = null;
        }
        return connectedDevicesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.ControlConfig)
    }

    static {
      defaultInstance = new ControlConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.ControlConfig)
  }

  public interface MaxConfigAdapterDeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.MaxConfigAdapterDevice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 deviceID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasDeviceID();
    /**
     * <code>required uint64 deviceID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    long getDeviceID();

    /**
     * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasPrimaryRS232Baud();
    /**
     * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbInterfaces.UartBaudrate getPrimaryRS232Baud();
  }
  /**
   * Protobuf type {@code maxpb.MaxConfigAdapterDevice}
   */
  public static final class MaxConfigAdapterDevice extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.MaxConfigAdapterDevice)
      MaxConfigAdapterDeviceOrBuilder {
    // Use MaxConfigAdapterDevice.newBuilder() to construct.
    private MaxConfigAdapterDevice(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MaxConfigAdapterDevice(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MaxConfigAdapterDevice defaultInstance;
    public static MaxConfigAdapterDevice getDefaultInstance() {
      return defaultInstance;
    }

    public MaxConfigAdapterDevice getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MaxConfigAdapterDevice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceID_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              maxpb.MaxpbInterfaces.UartBaudrate value = maxpb.MaxpbInterfaces.UartBaudrate.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                primaryRS232Baud_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbAdapterControl.internal_static_maxpb_MaxConfigAdapterDevice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbAdapterControl.internal_static_maxpb_MaxConfigAdapterDevice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.class, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder.class);
    }

    public static com.google.protobuf.Parser<MaxConfigAdapterDevice> PARSER =
        new com.google.protobuf.AbstractParser<MaxConfigAdapterDevice>() {
      public MaxConfigAdapterDevice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MaxConfigAdapterDevice(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MaxConfigAdapterDevice> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private long deviceID_;
    /**
     * <code>required uint64 deviceID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasDeviceID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 deviceID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public long getDeviceID() {
      return deviceID_;
    }

    public static final int PRIMARYRS232BAUD_FIELD_NUMBER = 2;
    private maxpb.MaxpbInterfaces.UartBaudrate primaryRS232Baud_;
    /**
     * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasPrimaryRS232Baud() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbInterfaces.UartBaudrate getPrimaryRS232Baud() {
      return primaryRS232Baud_;
    }

    private void initFields() {
      deviceID_ = 0L;
      primaryRS232Baud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, deviceID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, primaryRS232Baud_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, deviceID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, primaryRS232Baud_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.MaxConfigAdapterDevice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.MaxConfigAdapterDevice)
        maxpb.MaxpbAdapterControl.MaxConfigAdapterDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_MaxConfigAdapterDevice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_MaxConfigAdapterDevice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.class, maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.Builder.class);
      }

      // Construct using maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        primaryRS232Baud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbAdapterControl.internal_static_maxpb_MaxConfigAdapterDevice_descriptor;
      }

      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice getDefaultInstanceForType() {
        return maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance();
      }

      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice build() {
        maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice buildPartial() {
        maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice result = new maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceID_ = deviceID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.primaryRS232Baud_ = primaryRS232Baud_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice) {
          return mergeFrom((maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice other) {
        if (other == maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice.getDefaultInstance()) return this;
        if (other.hasDeviceID()) {
          setDeviceID(other.getDeviceID());
        }
        if (other.hasPrimaryRS232Baud()) {
          setPrimaryRS232Baud(other.getPrimaryRS232Baud());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbAdapterControl.MaxConfigAdapterDevice) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long deviceID_ ;
      /**
       * <code>required uint64 deviceID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasDeviceID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 deviceID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public long getDeviceID() {
        return deviceID_;
      }
      /**
       * <code>required uint64 deviceID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setDeviceID(long value) {
        bitField0_ |= 0x00000001;
        deviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 deviceID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceID_ = 0L;
        onChanged();
        return this;
      }

      private maxpb.MaxpbInterfaces.UartBaudrate primaryRS232Baud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
      /**
       * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasPrimaryRS232Baud() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbInterfaces.UartBaudrate getPrimaryRS232Baud() {
        return primaryRS232Baud_;
      }
      /**
       * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setPrimaryRS232Baud(maxpb.MaxpbInterfaces.UartBaudrate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        primaryRS232Baud_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.UartBaudrate primaryRS232baud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearPrimaryRS232Baud() {
        bitField0_ = (bitField0_ & ~0x00000002);
        primaryRS232Baud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.MaxConfigAdapterDevice)
    }

    static {
      defaultInstance = new MaxConfigAdapterDevice(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.MaxConfigAdapterDevice)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_ControlConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_ControlConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_MaxConfigAdapterDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_MaxConfigAdapterDevice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033maxpb_adapter_control.proto\022\005maxpb\032\026ma" +
      "xpb_interfaces.proto\032\030maxpb_filetransfer" +
      ".proto\"\322\001\n\rControlConfig\0226\n\017adapterBaudr" +
      "ate\030\001 \003(\0132\035.maxpb.MaxConfigAdapterDevice" +
      "\022\023\n\013fingerprint\030\002 \001(\t\022\022\n\nversionApp\030\003 \001(" +
      "\t\022\'\n\013fileCommand\030\004 \001(\0132\022.maxpb.FileComma" +
      "nd\0227\n\020connectedDevices\030\005 \003(\0132\035.maxpb.Max" +
      "ConfigAdapterDevice\"Y\n\026MaxConfigAdapterD" +
      "evice\022\020\n\010deviceID\030\001 \002(\004\022-\n\020primaryRS232b" +
      "aud\030\002 \001(\0162\023.maxpb.UartBaudrate"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          maxpb.MaxpbInterfaces.getDescriptor(),
          maxpb.MaxpbFiletransfer.getDescriptor(),
        }, assigner);
    internal_static_maxpb_ControlConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maxpb_ControlConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_ControlConfig_descriptor,
        new java.lang.String[] { "AdapterBaudrate", "Fingerprint", "VersionApp", "FileCommand", "ConnectedDevices", });
    internal_static_maxpb_MaxConfigAdapterDevice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maxpb_MaxConfigAdapterDevice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_MaxConfigAdapterDevice_descriptor,
        new java.lang.String[] { "DeviceID", "PrimaryRS232Baud", });
    maxpb.MaxpbInterfaces.getDescriptor();
    maxpb.MaxpbFiletransfer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
