// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maxpb_network.proto

package maxpb;

public final class MaxpbNetwork {
  private MaxpbNetwork() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code maxpb.Network}
   */
  public enum Network
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>N_BROADCAST = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    N_BROADCAST(0, 0),
    /**
     * <code>N_TRACKER = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    N_TRACKER(1, 1),
    /**
     * <code>N_RS485A = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_RS485A(2, 2),
    /**
     * <code>N_RS485B = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_RS485B(3, 3),
    /**
     * <code>N_RS232A = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    N_RS232A(4, 4),
    /**
     * <code>N_RS232B = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_RS232B(5, 5),
    /**
     * <code>N_WIFI = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_WIFI(6, 6),
    /**
     * <code>N_GSM_GPRS = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    N_GSM_GPRS(7, 7),
    /**
     * <code>N_CAN1 = 8;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_CAN1(8, 8),
    /**
     * <code>N_CAN2 = 9;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_CAN2(9, 9),
    /**
     * <code>N_USB = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162
     * </pre>
     */
    N_USB(10, 10),
    /**
     * <code>N_ZIGBEE = 11;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_ZIGBEE(11, 11),
    /**
     * <code>N_LORA = 12;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    N_LORA(12, 12),
    /**
     * <code>N_SATELLITE_IDP = 13;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_SATELLITE_IDP(13, 13),
    /**
     * <code>N_SATELLITE = 14;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_SATELLITE(14, 14),
    /**
     * <code>N_LUA = 15;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_LUA(15, 15),
    /**
     * <code>N_BLUETOOTH = 16;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    N_BLUETOOTH(16, 16),
    /**
     * <code>N_UDP = 17;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_UDP(17, 17),
    /**
     * <code>N_CLOUD = 18;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    N_CLOUD(18, 18),
    /**
     * <code>N_RFU_01 = 19;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_01(19, 19),
    /**
     * <code>N_RFU_02 = 20;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_02(20, 20),
    /**
     * <code>N_RFU_03 = 21;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_03(21, 21),
    /**
     * <code>N_RFU_04 = 22;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_04(22, 22),
    /**
     * <code>N_RFU_05 = 23;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_05(23, 23),
    /**
     * <code>N_RFU_06 = 24;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_06(24, 24),
    /**
     * <code>N_RFU_07 = 25;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_07(25, 25),
    /**
     * <code>N_RFU_08 = 26;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_08(26, 26),
    /**
     * <code>N_RFU_09 = 27;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_09(27, 27),
    /**
     * <code>N_RFU_10 = 28;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    N_RFU_10(28, 28),
    ;

    /**
     * <code>N_BROADCAST = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public static final int N_BROADCAST_VALUE = 0;
    /**
     * <code>N_TRACKER = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    public static final int N_TRACKER_VALUE = 1;
    /**
     * <code>N_RS485A = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_RS485A_VALUE = 2;
    /**
     * <code>N_RS485B = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_RS485B_VALUE = 3;
    /**
     * <code>N_RS232A = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public static final int N_RS232A_VALUE = 4;
    /**
     * <code>N_RS232B = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_RS232B_VALUE = 5;
    /**
     * <code>N_WIFI = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_WIFI_VALUE = 6;
    /**
     * <code>N_GSM_GPRS = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    public static final int N_GSM_GPRS_VALUE = 7;
    /**
     * <code>N_CAN1 = 8;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_CAN1_VALUE = 8;
    /**
     * <code>N_CAN2 = 9;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_CAN2_VALUE = 9;
    /**
     * <code>N_USB = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162
     * </pre>
     */
    public static final int N_USB_VALUE = 10;
    /**
     * <code>N_ZIGBEE = 11;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_ZIGBEE_VALUE = 11;
    /**
     * <code>N_LORA = 12;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    public static final int N_LORA_VALUE = 12;
    /**
     * <code>N_SATELLITE_IDP = 13;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_SATELLITE_IDP_VALUE = 13;
    /**
     * <code>N_SATELLITE = 14;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_SATELLITE_VALUE = 14;
    /**
     * <code>N_LUA = 15;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_LUA_VALUE = 15;
    /**
     * <code>N_BLUETOOTH = 16;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180
     * </pre>
     */
    public static final int N_BLUETOOTH_VALUE = 16;
    /**
     * <code>N_UDP = 17;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_UDP_VALUE = 17;
    /**
     * <code>N_CLOUD = 18;</code>
     *
     * <pre>
     *&#47; SupportedBy: 
     * </pre>
     */
    public static final int N_CLOUD_VALUE = 18;
    /**
     * <code>N_RFU_01 = 19;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_01_VALUE = 19;
    /**
     * <code>N_RFU_02 = 20;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_02_VALUE = 20;
    /**
     * <code>N_RFU_03 = 21;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_03_VALUE = 21;
    /**
     * <code>N_RFU_04 = 22;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_04_VALUE = 22;
    /**
     * <code>N_RFU_05 = 23;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_05_VALUE = 23;
    /**
     * <code>N_RFU_06 = 24;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_06_VALUE = 24;
    /**
     * <code>N_RFU_07 = 25;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_07_VALUE = 25;
    /**
     * <code>N_RFU_08 = 26;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_08_VALUE = 26;
    /**
     * <code>N_RFU_09 = 27;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_09_VALUE = 27;
    /**
     * <code>N_RFU_10 = 28;</code>
     *
     * <pre>
     *&#47;&#64;excluded SupportedBy:
     * </pre>
     */
    public static final int N_RFU_10_VALUE = 28;


    public final int getNumber() { return value; }

    public static Network valueOf(int value) {
      switch (value) {
        case 0: return N_BROADCAST;
        case 1: return N_TRACKER;
        case 2: return N_RS485A;
        case 3: return N_RS485B;
        case 4: return N_RS232A;
        case 5: return N_RS232B;
        case 6: return N_WIFI;
        case 7: return N_GSM_GPRS;
        case 8: return N_CAN1;
        case 9: return N_CAN2;
        case 10: return N_USB;
        case 11: return N_ZIGBEE;
        case 12: return N_LORA;
        case 13: return N_SATELLITE_IDP;
        case 14: return N_SATELLITE;
        case 15: return N_LUA;
        case 16: return N_BLUETOOTH;
        case 17: return N_UDP;
        case 18: return N_CLOUD;
        case 19: return N_RFU_01;
        case 20: return N_RFU_02;
        case 21: return N_RFU_03;
        case 22: return N_RFU_04;
        case 23: return N_RFU_05;
        case 24: return N_RFU_06;
        case 25: return N_RFU_07;
        case 26: return N_RFU_08;
        case 27: return N_RFU_09;
        case 28: return N_RFU_10;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Network>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Network>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Network>() {
            public Network findValueByNumber(int number) {
              return Network.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maxpb.MaxpbNetwork.getDescriptor().getEnumTypes().get(0);
    }

    private static final Network[] VALUES = values();

    public static Network valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Network(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maxpb.Network)
  }

  public interface RoutingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.Routing)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .maxpb.Network fromNetwork = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    boolean hasFromNetwork();
    /**
     * <code>optional .maxpb.Network fromNetwork = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    maxpb.MaxpbNetwork.Network getFromNetwork();

    /**
     * <code>optional .maxpb.Network toNetwork = 64;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    boolean hasToNetwork();
    /**
     * <code>optional .maxpb.Network toNetwork = 64;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    maxpb.MaxpbNetwork.Network getToNetwork();
  }
  /**
   * Protobuf type {@code maxpb.Routing}
   *
   * <pre>
   *&#47;&#64;exclude
   * </pre>
   */
  public static final class Routing extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.Routing)
      RoutingOrBuilder {
    // Use Routing.newBuilder() to construct.
    private Routing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Routing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Routing defaultInstance;
    public static Routing getDefaultInstance() {
      return defaultInstance;
    }

    public Routing getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Routing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              maxpb.MaxpbNetwork.Network value = maxpb.MaxpbNetwork.Network.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                fromNetwork_ = value;
              }
              break;
            }
            case 512: {
              int rawValue = input.readEnum();
              maxpb.MaxpbNetwork.Network value = maxpb.MaxpbNetwork.Network.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(64, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                toNetwork_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbNetwork.internal_static_maxpb_Routing_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbNetwork.internal_static_maxpb_Routing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbNetwork.Routing.class, maxpb.MaxpbNetwork.Routing.Builder.class);
    }

    public static com.google.protobuf.Parser<Routing> PARSER =
        new com.google.protobuf.AbstractParser<Routing>() {
      public Routing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Routing(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Routing> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FROMNETWORK_FIELD_NUMBER = 1;
    private maxpb.MaxpbNetwork.Network fromNetwork_;
    /**
     * <code>optional .maxpb.Network fromNetwork = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public boolean hasFromNetwork() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .maxpb.Network fromNetwork = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public maxpb.MaxpbNetwork.Network getFromNetwork() {
      return fromNetwork_;
    }

    public static final int TONETWORK_FIELD_NUMBER = 64;
    private maxpb.MaxpbNetwork.Network toNetwork_;
    /**
     * <code>optional .maxpb.Network toNetwork = 64;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public boolean hasToNetwork() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .maxpb.Network toNetwork = 64;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public maxpb.MaxpbNetwork.Network getToNetwork() {
      return toNetwork_;
    }

    private void initFields() {
      fromNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
      toNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, fromNetwork_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(64, toNetwork_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, fromNetwork_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(64, toNetwork_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbNetwork.Routing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.Routing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbNetwork.Routing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbNetwork.Routing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbNetwork.Routing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.Routing}
     *
     * <pre>
     *&#47;&#64;exclude
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.Routing)
        maxpb.MaxpbNetwork.RoutingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_Routing_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_Routing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbNetwork.Routing.class, maxpb.MaxpbNetwork.Routing.Builder.class);
      }

      // Construct using maxpb.MaxpbNetwork.Routing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
        bitField0_ = (bitField0_ & ~0x00000001);
        toNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_Routing_descriptor;
      }

      public maxpb.MaxpbNetwork.Routing getDefaultInstanceForType() {
        return maxpb.MaxpbNetwork.Routing.getDefaultInstance();
      }

      public maxpb.MaxpbNetwork.Routing build() {
        maxpb.MaxpbNetwork.Routing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbNetwork.Routing buildPartial() {
        maxpb.MaxpbNetwork.Routing result = new maxpb.MaxpbNetwork.Routing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromNetwork_ = fromNetwork_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toNetwork_ = toNetwork_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbNetwork.Routing) {
          return mergeFrom((maxpb.MaxpbNetwork.Routing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbNetwork.Routing other) {
        if (other == maxpb.MaxpbNetwork.Routing.getDefaultInstance()) return this;
        if (other.hasFromNetwork()) {
          setFromNetwork(other.getFromNetwork());
        }
        if (other.hasToNetwork()) {
          setToNetwork(other.getToNetwork());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbNetwork.Routing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbNetwork.Routing) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private maxpb.MaxpbNetwork.Network fromNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
      /**
       * <code>optional .maxpb.Network fromNetwork = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public boolean hasFromNetwork() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .maxpb.Network fromNetwork = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public maxpb.MaxpbNetwork.Network getFromNetwork() {
        return fromNetwork_;
      }
      /**
       * <code>optional .maxpb.Network fromNetwork = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder setFromNetwork(maxpb.MaxpbNetwork.Network value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        fromNetwork_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.Network fromNetwork = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder clearFromNetwork() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
        onChanged();
        return this;
      }

      private maxpb.MaxpbNetwork.Network toNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
      /**
       * <code>optional .maxpb.Network toNetwork = 64;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public boolean hasToNetwork() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .maxpb.Network toNetwork = 64;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public maxpb.MaxpbNetwork.Network getToNetwork() {
        return toNetwork_;
      }
      /**
       * <code>optional .maxpb.Network toNetwork = 64;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder setToNetwork(maxpb.MaxpbNetwork.Network value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        toNetwork_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.Network toNetwork = 64;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder clearToNetwork() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toNetwork_ = maxpb.MaxpbNetwork.Network.N_BROADCAST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.Routing)
    }

    static {
      defaultInstance = new Routing(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.Routing)
  }

  public interface RoutePackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.RoutePack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 devideID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasDevideID();
    /**
     * <code>required uint32 devideID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    int getDevideID();

    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    boolean hasIdentificationPack();
    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbReport.IDPack getIdentificationPack();
    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    maxpb.MaxpbReport.IDPackOrBuilder getIdentificationPackOrBuilder();

    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    boolean hasRoute();
    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    maxpb.MaxpbNetwork.Routing getRoute();
    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    maxpb.MaxpbNetwork.RoutingOrBuilder getRouteOrBuilder();

    /**
     * <code>required bytes data = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code maxpb.RoutePack}
   *
   * <pre>
   *&#47;&#64;exclude
   * </pre>
   */
  public static final class RoutePack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.RoutePack)
      RoutePackOrBuilder {
    // Use RoutePack.newBuilder() to construct.
    private RoutePack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RoutePack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RoutePack defaultInstance;
    public static RoutePack getDefaultInstance() {
      return defaultInstance;
    }

    public RoutePack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RoutePack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              devideID_ = input.readUInt32();
              break;
            }
            case 18: {
              maxpb.MaxpbReport.IDPack.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = identificationPack_.toBuilder();
              }
              identificationPack_ = input.readMessage(maxpb.MaxpbReport.IDPack.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(identificationPack_);
                identificationPack_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              maxpb.MaxpbNetwork.Routing.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = route_.toBuilder();
              }
              route_ = input.readMessage(maxpb.MaxpbNetwork.Routing.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(route_);
                route_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbNetwork.internal_static_maxpb_RoutePack_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbNetwork.internal_static_maxpb_RoutePack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbNetwork.RoutePack.class, maxpb.MaxpbNetwork.RoutePack.Builder.class);
    }

    public static com.google.protobuf.Parser<RoutePack> PARSER =
        new com.google.protobuf.AbstractParser<RoutePack>() {
      public RoutePack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoutePack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RoutePack> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVIDEID_FIELD_NUMBER = 1;
    private int devideID_;
    /**
     * <code>required uint32 devideID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasDevideID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 devideID = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public int getDevideID() {
      return devideID_;
    }

    public static final int IDENTIFICATIONPACK_FIELD_NUMBER = 2;
    private maxpb.MaxpbReport.IDPack identificationPack_;
    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public boolean hasIdentificationPack() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbReport.IDPack getIdentificationPack() {
      return identificationPack_;
    }
    /**
     * <code>optional .maxpb.IDPack identificationPack = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy:
     * </pre>
     */
    public maxpb.MaxpbReport.IDPackOrBuilder getIdentificationPackOrBuilder() {
      return identificationPack_;
    }

    public static final int ROUTE_FIELD_NUMBER = 3;
    private maxpb.MaxpbNetwork.Routing route_;
    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public boolean hasRoute() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public maxpb.MaxpbNetwork.Routing getRoute() {
      return route_;
    }
    /**
     * <code>required .maxpb.Routing route = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public maxpb.MaxpbNetwork.RoutingOrBuilder getRouteOrBuilder() {
      return route_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes data = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      devideID_ = 0;
      identificationPack_ = maxpb.MaxpbReport.IDPack.getDefaultInstance();
      route_ = maxpb.MaxpbNetwork.Routing.getDefaultInstance();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDevideID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, devideID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, identificationPack_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, route_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, devideID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, identificationPack_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, route_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbNetwork.RoutePack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbNetwork.RoutePack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.RoutePack}
     *
     * <pre>
     *&#47;&#64;exclude
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.RoutePack)
        maxpb.MaxpbNetwork.RoutePackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_RoutePack_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_RoutePack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbNetwork.RoutePack.class, maxpb.MaxpbNetwork.RoutePack.Builder.class);
      }

      // Construct using maxpb.MaxpbNetwork.RoutePack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdentificationPackFieldBuilder();
          getRouteFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        devideID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (identificationPackBuilder_ == null) {
          identificationPack_ = maxpb.MaxpbReport.IDPack.getDefaultInstance();
        } else {
          identificationPackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (routeBuilder_ == null) {
          route_ = maxpb.MaxpbNetwork.Routing.getDefaultInstance();
        } else {
          routeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbNetwork.internal_static_maxpb_RoutePack_descriptor;
      }

      public maxpb.MaxpbNetwork.RoutePack getDefaultInstanceForType() {
        return maxpb.MaxpbNetwork.RoutePack.getDefaultInstance();
      }

      public maxpb.MaxpbNetwork.RoutePack build() {
        maxpb.MaxpbNetwork.RoutePack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbNetwork.RoutePack buildPartial() {
        maxpb.MaxpbNetwork.RoutePack result = new maxpb.MaxpbNetwork.RoutePack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.devideID_ = devideID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (identificationPackBuilder_ == null) {
          result.identificationPack_ = identificationPack_;
        } else {
          result.identificationPack_ = identificationPackBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (routeBuilder_ == null) {
          result.route_ = route_;
        } else {
          result.route_ = routeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbNetwork.RoutePack) {
          return mergeFrom((maxpb.MaxpbNetwork.RoutePack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbNetwork.RoutePack other) {
        if (other == maxpb.MaxpbNetwork.RoutePack.getDefaultInstance()) return this;
        if (other.hasDevideID()) {
          setDevideID(other.getDevideID());
        }
        if (other.hasIdentificationPack()) {
          mergeIdentificationPack(other.getIdentificationPack());
        }
        if (other.hasRoute()) {
          mergeRoute(other.getRoute());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDevideID()) {

          return false;
        }
        if (!hasRoute()) {

          return false;
        }
        if (!hasData()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbNetwork.RoutePack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbNetwork.RoutePack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int devideID_ ;
      /**
       * <code>required uint32 devideID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasDevideID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 devideID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public int getDevideID() {
        return devideID_;
      }
      /**
       * <code>required uint32 devideID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setDevideID(int value) {
        bitField0_ |= 0x00000001;
        devideID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 devideID = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearDevideID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        devideID_ = 0;
        onChanged();
        return this;
      }

      private maxpb.MaxpbReport.IDPack identificationPack_ = maxpb.MaxpbReport.IDPack.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          MaxpbReport.IDPack, MaxpbReport.IDPack.Builder, MaxpbReport.IDPackOrBuilder> identificationPackBuilder_;
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public boolean hasIdentificationPack() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbReport.IDPack getIdentificationPack() {
        if (identificationPackBuilder_ == null) {
          return identificationPack_;
        } else {
          return identificationPackBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setIdentificationPack(maxpb.MaxpbReport.IDPack value) {
        if (identificationPackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          identificationPack_ = value;
          onChanged();
        } else {
          identificationPackBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder setIdentificationPack(
          maxpb.MaxpbReport.IDPack.Builder builderForValue) {
        if (identificationPackBuilder_ == null) {
          identificationPack_ = builderForValue.build();
          onChanged();
        } else {
          identificationPackBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder mergeIdentificationPack(maxpb.MaxpbReport.IDPack value) {
        if (identificationPackBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              identificationPack_ != maxpb.MaxpbReport.IDPack.getDefaultInstance()) {
            identificationPack_ =
              maxpb.MaxpbReport.IDPack.newBuilder(identificationPack_).mergeFrom(value).buildPartial();
          } else {
            identificationPack_ = value;
          }
          onChanged();
        } else {
          identificationPackBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public Builder clearIdentificationPack() {
        if (identificationPackBuilder_ == null) {
          identificationPack_ = maxpb.MaxpbReport.IDPack.getDefaultInstance();
          onChanged();
        } else {
          identificationPackBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbReport.IDPack.Builder getIdentificationPackBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIdentificationPackFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      public maxpb.MaxpbReport.IDPackOrBuilder getIdentificationPackOrBuilder() {
        if (identificationPackBuilder_ != null) {
          return identificationPackBuilder_.getMessageOrBuilder();
        } else {
          return identificationPack_;
        }
      }
      /**
       * <code>optional .maxpb.IDPack identificationPack = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy:
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          MaxpbReport.IDPack, MaxpbReport.IDPack.Builder, MaxpbReport.IDPackOrBuilder>
          getIdentificationPackFieldBuilder() {
        if (identificationPackBuilder_ == null) {
          identificationPackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              MaxpbReport.IDPack, MaxpbReport.IDPack.Builder, MaxpbReport.IDPackOrBuilder>(
                  getIdentificationPack(),
                  getParentForChildren(),
                  isClean());
          identificationPack_ = null;
        }
        return identificationPackBuilder_;
      }

      private maxpb.MaxpbNetwork.Routing route_ = maxpb.MaxpbNetwork.Routing.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Routing, Routing.Builder, RoutingOrBuilder> routeBuilder_;
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public boolean hasRoute() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public maxpb.MaxpbNetwork.Routing getRoute() {
        if (routeBuilder_ == null) {
          return route_;
        } else {
          return routeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder setRoute(maxpb.MaxpbNetwork.Routing value) {
        if (routeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          route_ = value;
          onChanged();
        } else {
          routeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder setRoute(
          maxpb.MaxpbNetwork.Routing.Builder builderForValue) {
        if (routeBuilder_ == null) {
          route_ = builderForValue.build();
          onChanged();
        } else {
          routeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder mergeRoute(maxpb.MaxpbNetwork.Routing value) {
        if (routeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              route_ != maxpb.MaxpbNetwork.Routing.getDefaultInstance()) {
            route_ =
              maxpb.MaxpbNetwork.Routing.newBuilder(route_).mergeFrom(value).buildPartial();
          } else {
            route_ = value;
          }
          onChanged();
        } else {
          routeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder clearRoute() {
        if (routeBuilder_ == null) {
          route_ = maxpb.MaxpbNetwork.Routing.getDefaultInstance();
          onChanged();
        } else {
          routeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public maxpb.MaxpbNetwork.Routing.Builder getRouteBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRouteFieldBuilder().getBuilder();
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public maxpb.MaxpbNetwork.RoutingOrBuilder getRouteOrBuilder() {
        if (routeBuilder_ != null) {
          return routeBuilder_.getMessageOrBuilder();
        } else {
          return route_;
        }
      }
      /**
       * <code>required .maxpb.Routing route = 3;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Routing, Routing.Builder, RoutingOrBuilder>
          getRouteFieldBuilder() {
        if (routeBuilder_ == null) {
          routeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Routing, Routing.Builder, RoutingOrBuilder>(
                  getRoute(),
                  getParentForChildren(),
                  isClean());
          route_ = null;
        }
        return routeBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes data = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 4;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MAXIO, MXT180
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.RoutePack)
    }

    static {
      defaultInstance = new RoutePack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.RoutePack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_Routing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_Routing_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_RoutePack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_RoutePack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023maxpb_network.proto\022\005maxpb\032\022maxpb_repo" +
      "rt.proto\"Q\n\007Routing\022#\n\013fromNetwork\030\001 \001(\016" +
      "2\016.maxpb.Network\022!\n\ttoNetwork\030@ \001(\0162\016.ma" +
      "xpb.Network\"u\n\tRoutePack\022\020\n\010devideID\030\001 \002" +
      "(\r\022)\n\022identificationPack\030\002 \001(\0132\r.maxpb.I" +
      "DPack\022\035\n\005route\030\003 \002(\0132\016.maxpb.Routing\022\014\n\004" +
      "data\030\004 \002(\014*\240\003\n\007Network\022\017\n\013N_BROADCAST\020\000\022" +
      "\r\n\tN_TRACKER\020\001\022\014\n\010N_RS485A\020\002\022\014\n\010N_RS485B" +
      "\020\003\022\014\n\010N_RS232A\020\004\022\014\n\010N_RS232B\020\005\022\n\n\006N_WIFI" +
      "\020\006\022\016\n\nN_GSM_GPRS\020\007\022\n\n\006N_CAN1\020\010\022\n\n\006N_CAN2",
      "\020\t\022\t\n\005N_USB\020\n\022\014\n\010N_ZIGBEE\020\013\022\n\n\006N_LORA\020\014\022" +
      "\023\n\017N_SATELLITE_IDP\020\r\022\017\n\013N_SATELLITE\020\016\022\t\n" +
      "\005N_LUA\020\017\022\017\n\013N_BLUETOOTH\020\020\022\t\n\005N_UDP\020\021\022\013\n\007" +
      "N_CLOUD\020\022\022\014\n\010N_RFU_01\020\023\022\014\n\010N_RFU_02\020\024\022\014\n" +
      "\010N_RFU_03\020\025\022\014\n\010N_RFU_04\020\026\022\014\n\010N_RFU_05\020\027\022" +
      "\014\n\010N_RFU_06\020\030\022\014\n\010N_RFU_07\020\031\022\014\n\010N_RFU_08\020" +
      "\032\022\014\n\010N_RFU_09\020\033\022\014\n\010N_RFU_10\020\034"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          maxpb.MaxpbReport.getDescriptor(),
        }, assigner);
    internal_static_maxpb_Routing_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maxpb_Routing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_Routing_descriptor,
        new java.lang.String[] { "FromNetwork", "ToNetwork", });
    internal_static_maxpb_RoutePack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maxpb_RoutePack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_RoutePack_descriptor,
        new java.lang.String[] { "DevideID", "IdentificationPack", "Route", "Data", });
    maxpb.MaxpbReport.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
