// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maxpb_accessories.proto

package maxpb;

public final class MaxpbAccessories {
  private MaxpbAccessories() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code maxpb.ProductModel}
   */
  public enum ProductModel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DT_NONE = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_NONE(0, 0),
    /**
     * <code>DT_MAXIO = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MAXIO(1, 1),
    /**
     * <code>DT_A40A = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_A40A(2, 10),
    /**
     * <code>DT_A40B = 11;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_A40B(3, 11),
    /**
     * <code>DT_MXT130 = 20;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT130(4, 20),
    /**
     * <code>DT_MXT132 = 21;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT132(5, 21),
    /**
     * <code>DT_MXT160 = 30;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT160(6, 30),
    /**
     * <code>DT_MXT162 = 31;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT162(7, 31),
    /**
     * <code>DT_MXT180 = 40;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT180(8, 40),
    /**
     * <code>DT_MXT184 = 41;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT184(9, 41),
    /**
     * <code>DT_MXT188 = 42;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT188(10, 42),
    /**
     * <code>DT_MXT189 = 43;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_MXT189(11, 43),
    /**
     * <code>DT_WT180 = 50;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_WT180(12, 50),
    /**
     * <code>DT_WT184 = 51;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    DT_WT184(13, 51),
    ;

    /**
     * <code>DT_NONE = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_NONE_VALUE = 0;
    /**
     * <code>DT_MAXIO = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MAXIO_VALUE = 1;
    /**
     * <code>DT_A40A = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_A40A_VALUE = 10;
    /**
     * <code>DT_A40B = 11;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_A40B_VALUE = 11;
    /**
     * <code>DT_MXT130 = 20;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT130_VALUE = 20;
    /**
     * <code>DT_MXT132 = 21;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT132_VALUE = 21;
    /**
     * <code>DT_MXT160 = 30;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT160_VALUE = 30;
    /**
     * <code>DT_MXT162 = 31;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT162_VALUE = 31;
    /**
     * <code>DT_MXT180 = 40;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT180_VALUE = 40;
    /**
     * <code>DT_MXT184 = 41;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT184_VALUE = 41;
    /**
     * <code>DT_MXT188 = 42;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT188_VALUE = 42;
    /**
     * <code>DT_MXT189 = 43;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_MXT189_VALUE = 43;
    /**
     * <code>DT_WT180 = 50;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_WT180_VALUE = 50;
    /**
     * <code>DT_WT184 = 51;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, A40
     * </pre>
     */
    public static final int DT_WT184_VALUE = 51;


    public final int getNumber() { return value; }

    public static ProductModel valueOf(int value) {
      switch (value) {
        case 0: return DT_NONE;
        case 1: return DT_MAXIO;
        case 10: return DT_A40A;
        case 11: return DT_A40B;
        case 20: return DT_MXT130;
        case 21: return DT_MXT132;
        case 30: return DT_MXT160;
        case 31: return DT_MXT162;
        case 40: return DT_MXT180;
        case 41: return DT_MXT184;
        case 42: return DT_MXT188;
        case 43: return DT_MXT189;
        case 50: return DT_WT180;
        case 51: return DT_WT184;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProductModel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProductModel>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProductModel>() {
            public ProductModel findValueByNumber(int number) {
              return ProductModel.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maxpb.MaxpbAccessories.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProductModel[] VALUES = values();

    public static ProductModel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProductModel(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maxpb.ProductModel)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027maxpb_accessories.proto\022\005maxpb*\327\001\n\014Pro" +
      "ductModel\022\013\n\007DT_NONE\020\000\022\014\n\010DT_MAXIO\020\001\022\013\n\007" +
      "DT_A40A\020\n\022\013\n\007DT_A40B\020\013\022\r\n\tDT_MXT130\020\024\022\r\n" +
      "\tDT_MXT132\020\025\022\r\n\tDT_MXT160\020\036\022\r\n\tDT_MXT162" +
      "\020\037\022\r\n\tDT_MXT180\020(\022\r\n\tDT_MXT184\020)\022\r\n\tDT_M" +
      "XT188\020*\022\r\n\tDT_MXT189\020+\022\014\n\010DT_WT180\0202\022\014\n\010" +
      "DT_WT184\0203"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
