// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maxpb_interfaces.proto

package maxpb;

public final class MaxpbInterfaces {
  private MaxpbInterfaces() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code maxpb.CanBitRate}
   */
  public enum CanBitRate
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CBR_NONE = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_NONE(0, 0),
    /**
     * <code>CBR_10000 = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_10000(1, 1),
    /**
     * <code>CBR_20000 = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_20000(2, 2),
    /**
     * <code>CBR_50000 = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_50000(3, 3),
    /**
     * <code>CBR_83333 = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_83333(4, 4),
    /**
     * <code>CBR_100000 = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_100000(5, 5),
    /**
     * <code>CBR_125000 = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_125000(6, 6),
    /**
     * <code>CBR_250000 = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_250000(7, 7),
    /**
     * <code>CBR_500000 = 8;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_500000(8, 8),
    /**
     * <code>CBR_800000 = 9;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_800000(9, 9),
    /**
     * <code>CBR_1000000 = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    CBR_1000000(10, 10),
    ;

    /**
     * <code>CBR_NONE = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_NONE_VALUE = 0;
    /**
     * <code>CBR_10000 = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_10000_VALUE = 1;
    /**
     * <code>CBR_20000 = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_20000_VALUE = 2;
    /**
     * <code>CBR_50000 = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_50000_VALUE = 3;
    /**
     * <code>CBR_83333 = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_83333_VALUE = 4;
    /**
     * <code>CBR_100000 = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_100000_VALUE = 5;
    /**
     * <code>CBR_125000 = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_125000_VALUE = 6;
    /**
     * <code>CBR_250000 = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_250000_VALUE = 7;
    /**
     * <code>CBR_500000 = 8;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_500000_VALUE = 8;
    /**
     * <code>CBR_800000 = 9;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_800000_VALUE = 9;
    /**
     * <code>CBR_1000000 = 10;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public static final int CBR_1000000_VALUE = 10;


    public final int getNumber() { return value; }

    public static CanBitRate valueOf(int value) {
      switch (value) {
        case 0: return CBR_NONE;
        case 1: return CBR_10000;
        case 2: return CBR_20000;
        case 3: return CBR_50000;
        case 4: return CBR_83333;
        case 5: return CBR_100000;
        case 6: return CBR_125000;
        case 7: return CBR_250000;
        case 8: return CBR_500000;
        case 9: return CBR_800000;
        case 10: return CBR_1000000;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CanBitRate>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CanBitRate>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CanBitRate>() {
            public CanBitRate findValueByNumber(int number) {
              return CanBitRate.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maxpb.MaxpbInterfaces.getDescriptor().getEnumTypes().get(0);
    }

    private static final CanBitRate[] VALUES = values();

    public static CanBitRate valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CanBitRate(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maxpb.CanBitRate)
  }

  /**
   * Protobuf enum {@code maxpb.UartBaudrate}
   */
  public enum UartBaudrate
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BAUD_9600 = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_9600(0, 0),
    /**
     * <code>BAUD_19200 = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_19200(1, 1),
    /**
     * <code>BAUD_38400 = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_38400(2, 2),
    /**
     * <code>BAUD_57600 = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_57600(3, 3),
    /**
     * <code>BAUD_115200 = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_115200(4, 4),
    /**
     * <code>BAUD_230400 = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    BAUD_230400(5, 5),
    /**
     * <code>BAUD_460800 = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO
     * </pre>
     */
    BAUD_460800(6, 6),
    /**
     * <code>BAUD_921600 = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO
     * </pre>
     */
    BAUD_921600(7, 7),
    ;

    /**
     * <code>BAUD_9600 = 0;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_9600_VALUE = 0;
    /**
     * <code>BAUD_19200 = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_19200_VALUE = 1;
    /**
     * <code>BAUD_38400 = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_38400_VALUE = 2;
    /**
     * <code>BAUD_57600 = 3;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_57600_VALUE = 3;
    /**
     * <code>BAUD_115200 = 4;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_115200_VALUE = 4;
    /**
     * <code>BAUD_230400 = 5;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public static final int BAUD_230400_VALUE = 5;
    /**
     * <code>BAUD_460800 = 6;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO
     * </pre>
     */
    public static final int BAUD_460800_VALUE = 6;
    /**
     * <code>BAUD_921600 = 7;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MAXIO
     * </pre>
     */
    public static final int BAUD_921600_VALUE = 7;


    public final int getNumber() { return value; }

    public static UartBaudrate valueOf(int value) {
      switch (value) {
        case 0: return BAUD_9600;
        case 1: return BAUD_19200;
        case 2: return BAUD_38400;
        case 3: return BAUD_57600;
        case 4: return BAUD_115200;
        case 5: return BAUD_230400;
        case 6: return BAUD_460800;
        case 7: return BAUD_921600;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UartBaudrate>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<UartBaudrate>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UartBaudrate>() {
            public UartBaudrate findValueByNumber(int number) {
              return UartBaudrate.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maxpb.MaxpbInterfaces.getDescriptor().getEnumTypes().get(1);
    }

    private static final UartBaudrate[] VALUES = values();

    public static UartBaudrate valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private UartBaudrate(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maxpb.UartBaudrate)
  }

  public interface PeripheralsConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.PeripheralsConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    boolean hasPrimarySerialChannelBaud();
    /**
     * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    maxpb.MaxpbInterfaces.UartBaudrate getPrimarySerialChannelBaud();

    /**
     * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MAXIO
     * </pre>
     */
    boolean hasSecondarySerialChannelBaud();
    /**
     * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MAXIO
     * </pre>
     */
    maxpb.MaxpbInterfaces.UartBaudrate getSecondarySerialChannelBaud();
  }
  /**
   * Protobuf type {@code maxpb.PeripheralsConfig}
   */
  public static final class PeripheralsConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.PeripheralsConfig)
      PeripheralsConfigOrBuilder {
    // Use PeripheralsConfig.newBuilder() to construct.
    private PeripheralsConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PeripheralsConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PeripheralsConfig defaultInstance;
    public static PeripheralsConfig getDefaultInstance() {
      return defaultInstance;
    }

    public PeripheralsConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PeripheralsConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              maxpb.MaxpbInterfaces.UartBaudrate value = maxpb.MaxpbInterfaces.UartBaudrate.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                primarySerialChannelBaud_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              maxpb.MaxpbInterfaces.UartBaudrate value = maxpb.MaxpbInterfaces.UartBaudrate.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                secondarySerialChannelBaud_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbInterfaces.internal_static_maxpb_PeripheralsConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbInterfaces.internal_static_maxpb_PeripheralsConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbInterfaces.PeripheralsConfig.class, maxpb.MaxpbInterfaces.PeripheralsConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<PeripheralsConfig> PARSER =
        new com.google.protobuf.AbstractParser<PeripheralsConfig>() {
      public PeripheralsConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeripheralsConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PeripheralsConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PRIMARYSERIALCHANNELBAUD_FIELD_NUMBER = 1;
    private maxpb.MaxpbInterfaces.UartBaudrate primarySerialChannelBaud_;
    /**
     * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public boolean hasPrimarySerialChannelBaud() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
     * </pre>
     */
    public maxpb.MaxpbInterfaces.UartBaudrate getPrimarySerialChannelBaud() {
      return primarySerialChannelBaud_;
    }

    public static final int SECONDARYSERIALCHANNELBAUD_FIELD_NUMBER = 2;
    private maxpb.MaxpbInterfaces.UartBaudrate secondarySerialChannelBaud_;
    /**
     * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MAXIO
     * </pre>
     */
    public boolean hasSecondarySerialChannelBaud() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MAXIO
     * </pre>
     */
    public maxpb.MaxpbInterfaces.UartBaudrate getSecondarySerialChannelBaud() {
      return secondarySerialChannelBaud_;
    }

    private void initFields() {
      primarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
      secondarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, primarySerialChannelBaud_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, secondarySerialChannelBaud_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, primarySerialChannelBaud_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, secondarySerialChannelBaud_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbInterfaces.PeripheralsConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbInterfaces.PeripheralsConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.PeripheralsConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.PeripheralsConfig)
        maxpb.MaxpbInterfaces.PeripheralsConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbInterfaces.internal_static_maxpb_PeripheralsConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbInterfaces.internal_static_maxpb_PeripheralsConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbInterfaces.PeripheralsConfig.class, maxpb.MaxpbInterfaces.PeripheralsConfig.Builder.class);
      }

      // Construct using maxpb.MaxpbInterfaces.PeripheralsConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        primarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        bitField0_ = (bitField0_ & ~0x00000001);
        secondarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbInterfaces.internal_static_maxpb_PeripheralsConfig_descriptor;
      }

      public maxpb.MaxpbInterfaces.PeripheralsConfig getDefaultInstanceForType() {
        return maxpb.MaxpbInterfaces.PeripheralsConfig.getDefaultInstance();
      }

      public maxpb.MaxpbInterfaces.PeripheralsConfig build() {
        maxpb.MaxpbInterfaces.PeripheralsConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbInterfaces.PeripheralsConfig buildPartial() {
        maxpb.MaxpbInterfaces.PeripheralsConfig result = new maxpb.MaxpbInterfaces.PeripheralsConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.primarySerialChannelBaud_ = primarySerialChannelBaud_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.secondarySerialChannelBaud_ = secondarySerialChannelBaud_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbInterfaces.PeripheralsConfig) {
          return mergeFrom((maxpb.MaxpbInterfaces.PeripheralsConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbInterfaces.PeripheralsConfig other) {
        if (other == maxpb.MaxpbInterfaces.PeripheralsConfig.getDefaultInstance()) return this;
        if (other.hasPrimarySerialChannelBaud()) {
          setPrimarySerialChannelBaud(other.getPrimarySerialChannelBaud());
        }
        if (other.hasSecondarySerialChannelBaud()) {
          setSecondarySerialChannelBaud(other.getSecondarySerialChannelBaud());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbInterfaces.PeripheralsConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbInterfaces.PeripheralsConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private maxpb.MaxpbInterfaces.UartBaudrate primarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
      /**
       * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
       * </pre>
       */
      public boolean hasPrimarySerialChannelBaud() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
       * </pre>
       */
      public maxpb.MaxpbInterfaces.UartBaudrate getPrimarySerialChannelBaud() {
        return primarySerialChannelBaud_;
      }
      /**
       * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
       * </pre>
       */
      public Builder setPrimarySerialChannelBaud(maxpb.MaxpbInterfaces.UartBaudrate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        primarySerialChannelBaud_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.UartBaudrate primarySerialChannelBaud = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT160, MXT162, MXT180, MAXIO
       * </pre>
       */
      public Builder clearPrimarySerialChannelBaud() {
        bitField0_ = (bitField0_ & ~0x00000001);
        primarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        onChanged();
        return this;
      }

      private maxpb.MaxpbInterfaces.UartBaudrate secondarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
      /**
       * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MAXIO
       * </pre>
       */
      public boolean hasSecondarySerialChannelBaud() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MAXIO
       * </pre>
       */
      public maxpb.MaxpbInterfaces.UartBaudrate getSecondarySerialChannelBaud() {
        return secondarySerialChannelBaud_;
      }
      /**
       * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MAXIO
       * </pre>
       */
      public Builder setSecondarySerialChannelBaud(maxpb.MaxpbInterfaces.UartBaudrate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        secondarySerialChannelBaud_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.UartBaudrate secondarySerialChannelBaud = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MAXIO
       * </pre>
       */
      public Builder clearSecondarySerialChannelBaud() {
        bitField0_ = (bitField0_ & ~0x00000002);
        secondarySerialChannelBaud_ = maxpb.MaxpbInterfaces.UartBaudrate.BAUD_9600;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.PeripheralsConfig)
    }

    static {
      defaultInstance = new PeripheralsConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.PeripheralsConfig)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_PeripheralsConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_PeripheralsConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026maxpb_interfaces.proto\022\005maxpb\"\203\001\n\021Peri" +
      "pheralsConfig\0225\n\030primarySerialChannelBau" +
      "d\030\001 \001(\0162\023.maxpb.UartBaudrate\0227\n\032secondar" +
      "ySerialChannelBaud\030\002 \001(\0162\023.maxpb.UartBau" +
      "drate*\267\001\n\nCanBitRate\022\014\n\010CBR_NONE\020\000\022\r\n\tCB" +
      "R_10000\020\001\022\r\n\tCBR_20000\020\002\022\r\n\tCBR_50000\020\003\022" +
      "\r\n\tCBR_83333\020\004\022\016\n\nCBR_100000\020\005\022\016\n\nCBR_12" +
      "5000\020\006\022\016\n\nCBR_250000\020\007\022\016\n\nCBR_500000\020\010\022\016" +
      "\n\nCBR_800000\020\t\022\017\n\013CBR_1000000\020\n*\221\001\n\014Uart" +
      "Baudrate\022\r\n\tBAUD_9600\020\000\022\016\n\nBAUD_19200\020\001\022",
      "\016\n\nBAUD_38400\020\002\022\016\n\nBAUD_57600\020\003\022\017\n\013BAUD_" +
      "115200\020\004\022\017\n\013BAUD_230400\020\005\022\017\n\013BAUD_460800" +
      "\020\006\022\017\n\013BAUD_921600\020\007"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maxpb_PeripheralsConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maxpb_PeripheralsConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_PeripheralsConfig_descriptor,
        new java.lang.String[] { "PrimarySerialChannelBaud", "SecondarySerialChannelBaud", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
