// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maxpb_ioexpander.proto

package maxpb;

public final class MaxpbIoexpander {
  private MaxpbIoexpander() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VehicleSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maxpb.VehicleSignature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    boolean hasBitRate();
    /**
     * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    maxpb.MaxpbInterfaces.CanBitRate getBitRate();

    /**
     * <code>optional bytes vehicleKey = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    boolean hasVehicleKey();
    /**
     * <code>optional bytes vehicleKey = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    com.google.protobuf.ByteString getVehicleKey();
  }
  /**
   * Protobuf type {@code maxpb.VehicleSignature}
   *
   * <pre>
   *&#47; This messaged is used to report the vehicle signature and ask a library that fits
   * </pre>
   */
  public static final class VehicleSignature extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:maxpb.VehicleSignature)
      VehicleSignatureOrBuilder {
    // Use VehicleSignature.newBuilder() to construct.
    private VehicleSignature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VehicleSignature(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VehicleSignature defaultInstance;
    public static VehicleSignature getDefaultInstance() {
      return defaultInstance;
    }

    public VehicleSignature getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleSignature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              maxpb.MaxpbInterfaces.CanBitRate value = maxpb.MaxpbInterfaces.CanBitRate.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                bitRate_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              vehicleKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maxpb.MaxpbIoexpander.internal_static_maxpb_VehicleSignature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maxpb.MaxpbIoexpander.internal_static_maxpb_VehicleSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maxpb.MaxpbIoexpander.VehicleSignature.class, maxpb.MaxpbIoexpander.VehicleSignature.Builder.class);
    }

    public static com.google.protobuf.Parser<VehicleSignature> PARSER =
        new com.google.protobuf.AbstractParser<VehicleSignature>() {
      public VehicleSignature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleSignature(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleSignature> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BITRATE_FIELD_NUMBER = 1;
    private maxpb.MaxpbInterfaces.CanBitRate bitRate_;
    /**
     * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public boolean hasBitRate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public maxpb.MaxpbInterfaces.CanBitRate getBitRate() {
      return bitRate_;
    }

    public static final int VEHICLEKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString vehicleKey_;
    /**
     * <code>optional bytes vehicleKey = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public boolean hasVehicleKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes vehicleKey = 2;</code>
     *
     * <pre>
     *&#47; SupportedBy: MXT162, MAXIO
     * </pre>
     */
    public com.google.protobuf.ByteString getVehicleKey() {
      return vehicleKey_;
    }

    private void initFields() {
      bitRate_ = maxpb.MaxpbInterfaces.CanBitRate.CBR_NONE;
      vehicleKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, bitRate_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, vehicleKey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, bitRate_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, vehicleKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static maxpb.MaxpbIoexpander.VehicleSignature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(maxpb.MaxpbIoexpander.VehicleSignature prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maxpb.VehicleSignature}
     *
     * <pre>
     *&#47; This messaged is used to report the vehicle signature and ask a library that fits
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maxpb.VehicleSignature)
        maxpb.MaxpbIoexpander.VehicleSignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maxpb.MaxpbIoexpander.internal_static_maxpb_VehicleSignature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maxpb.MaxpbIoexpander.internal_static_maxpb_VehicleSignature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maxpb.MaxpbIoexpander.VehicleSignature.class, maxpb.MaxpbIoexpander.VehicleSignature.Builder.class);
      }

      // Construct using maxpb.MaxpbIoexpander.VehicleSignature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bitRate_ = maxpb.MaxpbInterfaces.CanBitRate.CBR_NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        vehicleKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maxpb.MaxpbIoexpander.internal_static_maxpb_VehicleSignature_descriptor;
      }

      public maxpb.MaxpbIoexpander.VehicleSignature getDefaultInstanceForType() {
        return maxpb.MaxpbIoexpander.VehicleSignature.getDefaultInstance();
      }

      public maxpb.MaxpbIoexpander.VehicleSignature build() {
        maxpb.MaxpbIoexpander.VehicleSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maxpb.MaxpbIoexpander.VehicleSignature buildPartial() {
        maxpb.MaxpbIoexpander.VehicleSignature result = new maxpb.MaxpbIoexpander.VehicleSignature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bitRate_ = bitRate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vehicleKey_ = vehicleKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maxpb.MaxpbIoexpander.VehicleSignature) {
          return mergeFrom((maxpb.MaxpbIoexpander.VehicleSignature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maxpb.MaxpbIoexpander.VehicleSignature other) {
        if (other == maxpb.MaxpbIoexpander.VehicleSignature.getDefaultInstance()) return this;
        if (other.hasBitRate()) {
          setBitRate(other.getBitRate());
        }
        if (other.hasVehicleKey()) {
          setVehicleKey(other.getVehicleKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maxpb.MaxpbIoexpander.VehicleSignature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maxpb.MaxpbIoexpander.VehicleSignature) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private maxpb.MaxpbInterfaces.CanBitRate bitRate_ = maxpb.MaxpbInterfaces.CanBitRate.CBR_NONE;
      /**
       * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public boolean hasBitRate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public maxpb.MaxpbInterfaces.CanBitRate getBitRate() {
        return bitRate_;
      }
      /**
       * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public Builder setBitRate(maxpb.MaxpbInterfaces.CanBitRate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        bitRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .maxpb.CanBitRate bitRate = 1;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public Builder clearBitRate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bitRate_ = maxpb.MaxpbInterfaces.CanBitRate.CBR_NONE;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString vehicleKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes vehicleKey = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public boolean hasVehicleKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes vehicleKey = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public com.google.protobuf.ByteString getVehicleKey() {
        return vehicleKey_;
      }
      /**
       * <code>optional bytes vehicleKey = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public Builder setVehicleKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        vehicleKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes vehicleKey = 2;</code>
       *
       * <pre>
       *&#47; SupportedBy: MXT162, MAXIO
       * </pre>
       */
      public Builder clearVehicleKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vehicleKey_ = getDefaultInstance().getVehicleKey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:maxpb.VehicleSignature)
    }

    static {
      defaultInstance = new VehicleSignature(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:maxpb.VehicleSignature)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maxpb_VehicleSignature_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_maxpb_VehicleSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026maxpb_ioexpander.proto\022\005maxpb\032\026maxpb_i" +
      "nterfaces.proto\"J\n\020VehicleSignature\022\"\n\007b" +
      "itRate\030\001 \001(\0162\021.maxpb.CanBitRate\022\022\n\nvehic" +
      "leKey\030\002 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          maxpb.MaxpbInterfaces.getDescriptor(),
        }, assigner);
    internal_static_maxpb_VehicleSignature_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maxpb_VehicleSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_maxpb_VehicleSignature_descriptor,
        new java.lang.String[] { "BitRate", "VehicleKey", });
    maxpb.MaxpbInterfaces.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
